version: '3.7'

services:
  apache:
    container_name: kp-test-apache
    build:
      context: ./docker/apache
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
    networks:
      - kp-test-network
    entrypoint: /usr/local/bin/entrypoint.sh

  db:
    container_name: kp-test-db
    image: mysql:8.1.0-oracle
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: my_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - kp-test-network

  adminer:
    container_name: kp-test-adminer
    image: adminer
    restart: always
    ports:
      - "8888:8080"
    networks:
      - kp-test-network

volumes:
  db_data:

networks:
  kp-test-network:
    driver: bridge
